SELECT MA_NVIEN, MADA
FROM PHANCONG PC1
WHERE NOT EXISTS
				(SELECT MADA
				FROM DEAN
				WHERE MADA IN (SELECT MADA
								FROM PHANCONG
								WHERE MA_NVIEN = '005')
								AND MADA NOT IN (SELECT MADA
												FROM PHANCONG
												WHERE MA_NVIEN = PC1.MA_NVIEN))